### ISSUE TITLE
i cant play anything 🚫 ope: Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by CallumKoolaid** [museofficial/muse#985]
**What's happening?**
Concisely describe what's going wrong.
i cant play anything from youtube or spotify
youtube play error 🚫 ope: Response code 403 (Forbidden)

spotify play error 🚫 ope: no songs found
i have double checked all the values for the docker compose like spotify id and youtube token
ive also tried the same config on a vm and same issue
**Logs**
logs dont show anything only the basic message when it first boots

```

```

**Screenshots**
https://i.imgur.com/vWDNTrJ.png
**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [* ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse:latest
- Docker (if applicable):Docker version 20.10.24, build 297e128
- OS:ubuntu server 64bit
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by codetheweb** [comment]
It looks like YouTube is blocking your requests. Are you able to try from a different public IP?

**Comment by narendnp** [comment]
> It looks like YouTube is blocking your requests. Are you able to try from a different public IP?

Same issue here, tried different IP, VPN, etc. still doesn't work.

**Comment by evanknight11** [comment]
Same issue, tried different IP, nothing helped.

**Comment by AlvaroMartinezB** [comment]
Same issue! Can't play YouTube nor Spotify

**Comment by AlvaroMartinezB** [comment]
Fixed it! Guess that's what we get for not following instructions:

YOUTUBE_API_KEY can be acquired by [creating a new project](https://console.developers.google.com/) in Google's Developer Console, **enabling the YouTube API**, and creating an API key under credentials.

I didn't enable the YouTube API when I created the API Key, I just enabled "YouTube Data API v3" on the Google Dashboard and now it works, both for spotify and Youtube

**Comment by LaserKaspar** [comment]
I get bad request 400 with a wrong API key and 403 with a correct one. When doing "/play yt-url"

I enabled Data API v3 at first now I enabled all. Still not working.
<img width="181" height="110" alt="Image" src="https://github.com/user-attachments/assets/7f0af8cd-d337-4552-83c6-364221761d1f" />
